export type Category =
  | "design-for-reliability"
  | "maintenance-engineering"
  | "reliability-safety";

export interface Article {
  slug: string;
  title: string;
  titleHe?: string;
  excerpt: string;
  excerptHe?: string;
  category: Category;
  date: string;
  readTime: number;
  featured?: boolean;
  content: string;
  contentHe?: string;
}

export const categoryLabels: Record<Category, { en: string; he: string }> = {
  "design-for-reliability": {
    en: "Design for Reliability",
    he: "עיצוב לאמינות",
  },
  "maintenance-engineering": {
    en: "Maintenance Engineering",
    he: "הנדסת תחזוקה",
  },
  "reliability-safety": {
    en: "Reliability & Safety",
    he: "אמינות ובטיחות",
  },
};

export const articles: Article[] = [
  {
    slug: "asset-maintenance-optimization-offshore-wind-farm",
    title:
      "Asset Maintenance Optimization: the Case-Study of an Offshore Wind Farm",
    titleHe: "אופטימיזציה של תחזוקת נכסים: מקרה בוחן של חוות רוח ימית",
    excerpt: `Offshore Wind Farms are costly assets, not only in the aspects of design and construction, but also in those of operation and maintenance. Their remote location, along with weather constraints, harsh marine environment, and lack of adapted access equipment, make their maintenance complicated and expensive due to high repair and transportation costs and painful production losses generated by high downtime.

Generally, offshore wind technology is in a stage where its economic viability has yet to be fully proven, and numerous projects are largely supported by governmental subsidies [1]. This lack of maturity is evident, for example, in the numerous reliability issues related to wind turbine components.

Both the inherent aspects of the offshore wind industry and the reliability problems it faces contribute to high Operation and Maintenance (O&M) costs, which eventually hinder its competitiveness compared to other sources of energy. It is commonly assumed that up to 25 % of the cost of energy produced by offshore wind turbines is generated by O&M activities – twice as much as with onshore installations [2].`,
    excerptHe:
      "חוות רוח ימיות הן נכסים יקרים, לא רק מבחינת עיצוב ובנייה, אלא גם מבחינת תפעול ותחזוקה. מקובל להניח שעד 25% מעלות האנרגיה המיוצרת בטורבינות רוח ימיות נוצרת מפעילויות O&M – פי שניים מאשר בהתקנות יבשתיות.",
    category: "maintenance-engineering",
    date: "2015-01-14",
    readTime: 12,
    featured: true,
    content: `Offshore Wind Farms are costly assets, not only in the aspects of design and construction, but also in those of operation and maintenance. Their remote location, along with weather constraints, harsh marine environment, and lack of adapted access equipment, make their maintenance complicated and expensive due to high repair and transportation costs and painful production losses generated by high downtime.

Generally, offshore wind technology is in a stage where its economic viability has yet to be fully proven, and numerous projects are largely supported by governmental subsidies [1]. This lack of maturity is evident, for example, in the numerous reliability issues related to wind turbine components.

Both the inherent aspects of the offshore wind industry and the reliability problems it faces contribute to high Operation and Maintenance (O&M) costs, which eventually hinder its competitiveness compared to other sources of energy. It is commonly assumed that up to 25 % of the cost of energy produced by offshore wind turbines is generated by O&M activities – twice as much as with onshore installations [2].

This article describes a methodology for optimizing the maintenance strategy of offshore wind farms, in order to minimize lifecycle costs, and maximize availability and performance. apmOptimizer, developed by BQR Reliability Engineering, [3] is an advanced software tool used for modelling, reliability analysis, cost and performance estimations, as well as maintenance optimization.

For the purpose of the demonstration, we have created a case study of a typical wind farm, including a detailed model covering numerous operational, cost and maintenance parameters. The apmOptimizer optimization modules are then implemented in order to optimize the preventive maintenance, periodical inspections, condition-based maintenance, and spare part levels. Starting from a baseline scenario, several optimization steps are investigated, following a typical RAM/LCC analysis assessment procedure: Operational Availability, Operational Downtime, Lifecycle O&M Costs and produced energy are used as the main metrics. The optimal maintenance strategy is obtained from an exact optimization process and not from Monte Carlo simulations, which can provide only an approximated assessment for a user-inputted strategy.

The case study clearly shows that by following several optimization steps, the wind farm's performance can be significantly increased, allowing the produced energy's cost to become substantially more competitive. The impact of modelling parameters such as failure distribution and degradation process is also investigated.

## 1. Background on the apmOptimizer

apmOptimizer is a Modelling, Analysis and Optimization tool designed to bring asset maintenance to an optimal state, maximize availability and minimize Cost of Ownership over lifetime. Optimization algorithms are implemented to identify the optimal solution among all possible outcomes, according to the problem constraints and targets. apmOptimizer is not based on the Monte Carlo method whose result accuracy is based upon the number of calculated simulations and is dependent on user's best guess, but, instead, performs exact analytical computations from the input data, including failure rate distribution and reliability model (serial, parallel, standby redundancy, K out of N). The optimization process itself is not user-driven, since the space of possible solutions is based on these exact computations. This guarantees that even non-evident solutions can be identified.

In this case study, apmOptimizer is used to build a model of a typical wind farm and calculate its Reliability Availability Maintainability (RAM) parameters, as well as Lifecycle Costs (LCC). The Energetic Performance of the wind farm is also computed and the cost of energy extracted. The apmOptimizer model can integrate the most specific features of a wind farm and of its maintenance operations: Accessibility limitations, weather variability, high cost of downtime, planned and unplanned maintenance, etc. Although this is not done in the present case study, operational data from an actual wind farm (maintenance records, log book, sensor readings) can also be used for a better assessment of failure distribution.

After defining and characterizing a baseline model, several scenarios have been created, that successively investigate the impact of preventive inspections, preventive replacements, and inventory level. Each of these scenarios is provided to apmOptimzer for optimization and RAM/LCC and Performance Metrics are compared.

## 2. Description of the Model

This case study's scope covers only a brief review of the main elements, and not a complete description of the input parameters. The authors would like to highlight the fact that the data used in this work was obtained from publicly available sources and unavailable data was assessed by engineering judgment.

### 2.1 Wind farm elements

The considered system is a 240MW wind farm, composed of 80 generic wind turbines, each with a rated power of 3MW, one offshore substation and submarine cables. Turbines are grouped in 8 clusters (radials), each containing 10 WT and cables. The farm is located at a medium distance of 30 km from shore. The wind farm (WF) operates on a 24/7 basis, with an expected lifetime of 20 years. Since this case study is focused on evaluating the costs related to O&M activities only, it is assumed that the wind farm is completely operational from year 1 and that commissioning and decommissioning phases are not considered for cost analysis.

It is assumed that each 3MW wind turbine is pitch-regulated, with variable speed, with gearbox installed, and is modeled by a breakdown structure, adapted from the Reliawind project [4]. For the sake of simplicity, the breakdown tree is limited to assembly level, and sub-assemblies and components are not modeled.

### 2.2 Failure and reliability parameters

The global wind turbine failure rate was assumed to be 3.8 failures/turbine/year, based on an initial onshore data, with a value of 1.5 and conversion coefficients K1=1.75 and K2=1.447 for environmental stress and near shore location respectively [5]. The components contribution to total wind turbine failure rate was then obtained from [6], where exponential distribution is assumed.

In accordance with [7] approach, we have defined several generic failure modes (FM) for each element of the wind turbine and for each failure mode a failure ratio (FR). For example, the gearbox (GB) has 3 failure modes defined.

The failure modes, having some inspection tasks, are defined as hidden (others are evident failure modes), meaning the failure cannot be detected until an inspection is performed. Failures detected by condition monitoring equipment are considered to be evident. Additionally, the degradation process of hidden failure modes is modeled by defining a "mean time from degradation start to failure", as well as a "deviation" parameter representing the uncertainty of the degradation process.

### 2.3 Maintenance tasks and resources

The failure modes are assigned some maintenance tasks and maintenance resources required to restore the equipment in accordance with [7].

The costs of personnel, support equipment, materials and other resources are defined in libraries and allocated to maintenance tasks. The wind farm is maintained by 20 technicians working 12 hours per day, 350 days a year at a cost of 70€ per hour. Operations personnel (stationed in a control room) is composed of 3 teams of 3 operators (8-hour shifts) at a cost of 50 Euros per hour.

### 2.4 Maintenance locations

Most of the maintenance tasks are performed on-site and only the heaviest repair tasks like blade or gearbox repair are performed in an on-shore maintenance facility. Spare parts are also stored in this facility, where they arrive from different suppliers or after repair. Spare parts procurement takes place on-demand and a time delay that accounts for production and/or administrative delays is defined for every replaceable item. For example, the blades procurement delay is 6 days. The maintenance locations and transportation between them are defined in the apmOptimizer through the maintenance map.

Several access vessels are defined between the wind farm and the maintenance facility:

- Cable laying vessel – used for cables
- Jack-up vessel – used for large parts
- Workboat access vessel – used for transporting personnel
- Diving support vessel – used for inspecting foundations

Wind turbines are equipped with an internal crane that can handle small parts, while larger parts require use of the Jack-up vessel.

Supply of spare parts to the maintenance facility is performed by a standard truck with an average transportation time of 20 hours, except for the blades, where a special truck is used, with an average transportation time of 120 hours.

### 2.5 Environmental parameters

The wind variability is the most significant factor in the energy production. Its variation is mostly seasonal and widely studied in professional literature [8]. In the present case study, wind speed variability is accounted for on an annual basis within the energy production module, by assuming a wind speed density function of Weibull type, with scale parameter A=8.09, shape parameter k=1.96 [9], and a rated power output curve of the Vestas V90 3MW WT. By combining this data with the reliability metrics of the wind farm components, the total produced energy at wind farm level, as well as its cost, can be extracted.

An initial performance computation yields an ideal (no failures) annual energy production of 960096 MWh.

The second major impact of the wind variability is its delaying of maintenance operations. This is accounted for in our study through additional mean transportation time delays incurred by the transportation vessels.

## 3. Baseline Scenario

### 3.1 Initial maintenance strategy

The basic assumptions of the initial maintenance strategy are described hereunder:

- Inspection of all components is performed once a year for all components.
- When an inspected item's degradation is too severe or has failed, a spare part is ordered from stock.
- If a spare item is available in stock, it is sent to a wind farm with required maintenance resources by using the appropriate vessel; if not, it is ordered from the supplier.
- Stock delay due to administrative constraints is assumed to be 24 hrs.
- Suppliers delays are item dependent (several days in all cases).
- Transportation delays incorporate: Mobilization time, transportation time, positioning time, and an assumed weather variability delay.
- When a spare part arrives at the wind farm, the item is removed and replaced by the new one.
- Failed item is taken back onshore for repair at repair facility according to defined tasks. A repair delay (for administrative procedures) of 2 days is assumed in addition to repair time.
- Repaired item is made available in stock.
- Some items have repair condemnation, meaning they can be repaired only a limited number of times, before they are disposed of. In this case, a new spare part is ordered.

### 3.2 Analysis Results

Computations are performed to extract the main characteristics of the wind turbine: Reliability metrics, performance metrics and cost metrics.

The pitch and yaw systems are clearly the main contributors to the downtime, along with the generator and gearbox. This is mostly due to a relatively high failure rate combined with a high turnaround time: When a part is in need of replacement, a long period of time is required for the jack-up vessel to be available and reach the wind farm, and in the meantime, the wind turbine is not operational. On the other hand, components with similar failure rates, such as frequency converters, contribute much less to the downtime since spare parts are brought to site faster by workboat vessels. In addition, the limited number of spare parts in stock is also a cause for downtime since more spare parts may be necessary for repair than available at stock, thus creating a spare waiting time.

The resulting WT availability is 80%, and the energy produced by the entire wind farm is 763697 MWh/year at a cost of 23.4 M€ (O&M only). The resulting cost of energy is 31€/MWh produced, and the capacity factor of the wind farm is 36.3%.

## 4. Optimization Scenarios

### 4.1 Inspections Optimization

The inspection schedule of the baseline scenario gives an identical weight to each WT component. While this approach is not unusual in existing installations, it is somewhat unjustified. An adapted inspection schedule should be able to improve the system availability by accounting for the different reliability rates and degradation process. The Inspection Optimization module of the apmOptimizer is used for performing the optimization, with the optimization objective being the minimization of total costs, i.e. maintenance costs, failure damage costs and downtime costs (revenue losses). Optionally, it is possible to define minimal required availability or reliability at component or system level. Since inspections are planned in advance, required spare parts can also be ordered in advance and provided on time.

Optimization yields very significant results: The WT availability increases by 7.3 points, which translates in a 9% increase in energy production. From the cost perspective, the effect is even more evident through a 26.5% reduction in corrective maintenance costs, as well as a reduction in preventive maintenance costs, due to better oriented inspections, although many more inspections are performed (inspections costs vary according to equipment). Overall, the cost of produced energy is reduced by about 30%.

The advantage of performing optimization by using an optimization algorithm, versus Monte Carlo type simulations, is clearly seen by looking at the proposed inspections schedule. The optimization algorithm is powerful enough to yield original solutions that provide the strongest cost reductions and performance improvements.

### 4.2 Condition Monitoring System Scenario – Preventive Maintenance Optimization

The effectiveness of implementing a CMS system is investigated here. CMS systems are useful in the case of offshore farms since they provide operator failure detection and identification, and enable scheduling a repair/replacement with much more precision. However, these systems are still expensive and do not always offer a clear view of what is really happening in the turbine.

In the present scenario, we assume that a CMS is installed on the following items: Gearbox, pitch system and yaw system (the main downtime drivers) and that their degradation is continuously measured. Coupled with an assumed prediction model, they enable predicting the time-to-failure (TTF) density distribution at a given time, and then decide on an optimal maintenance planning method that best accounts for maintenance costs and other maintenance tasks.

For the sake of comparison, an average investment cost of 1200 € per CMS system (total CMS cost of 288000€) has been included in the cost computations. Even with this additional cost, the implementation of CMS remains worthwhile and brings a reduction in O&M costs of more than 3.5M€ per year compared to the previous scenario. However, this improvement has to be tempered by the fact that the deployment of the CMS systems could affect the turbine's reliability, since the CMS may fail as well, and that we assume 100% of the degradations are clearly detected, although there are cases where signals cannot be clearly interpreted.

### 4.3 Spare part level optimization

Optimizing the inventory level of spare parts is an important stage in reducing downtime, especially for parts that have very long lead or turnaround time. After inspections and preventive maintenance have been optimized, the requirement for spares is modified and should be also optimized. For that purpose, we use the spares optimization module of the apmOptimizer. The optimization algorithm objective is to minimize the total costs and damage. The program provides the optimal initial spares quantity as well as the required spares that must be ordered during lifetime in order to replenish stocks of condemned parts.

As a result of the spare optimization, availability increases to 93.6%, as well as the energy produced. The reduction in corrective maintenance costs reflects a decrease in revenue losses due to downtime. The cost of energy produced decreases a little more to 14€/MWh.

## 5. Conclusions and future work

This case study has demonstrated the capabilities of apmOptimizer in efficiently modeling an offshore wind farm, and proposing original maintenance configurations to generate significant downtime and O&M cost reductions. Starting from a hypothetical yet representative baseline model, the inspection, preventive maintenance and spare parts modules have successively reduced the downtime and improved the total amount of energy produced. It has been shown that the knowledge of the failure modes of each component, and especially of the associated degradation process, enables defining the optimal inspection schedule and reducing the overall downtime.

The rationale behind using condition monitoring systems for early detection of the degradation process has been highlighted, and proven to be worth the investment. Moreover, the use of failure distributions extracted from on-site measurements was shown to be profitable for optimization of preventive replacements.

In a future case study, a more detailed model of the wind turbine components, as well as field data from real wind farms installations will be used to extract accurate reliability figures. This field data will be used to evaluate real failure distributions for all components instead of the usual assumptions.

## 6. References

- [1] European Wind Energy Association (EWEA) (2011), Wind in Our Sails.
- [2] Jannie Sonderkar Nielsen, PhD (2013) Risk-Based Operation and Maintenance of Offshore Wind Turbines, Aalborg University.
- [3] BQR Reliability Engineering Ltd, http://www.bqr.com
- [4] ReliaWind Deliverable D 6.7 (2010), Recommendations from the ReliaWind Consortium for the Standardisation for the Wind Industry of Wind Turbine Reliability Taxonomy, Terminology and Data Collection.
- [5] Alexander Karyotakis (2011) On the Optimisation of Operation and Maintenance Strategies for Offshore Wind Farms, Department of Mechanical Engineering, University College London.
- [6] ReliaWind Deliverable D.1.3 (2010), Report on Wind Turbine Reliability Profiles.
- [7] B. Maples, G. Saur, M. Hand, R. van de Pietermen and T. Obdam – NREL (2013), Installation, Operation, and Maintenance Strategies to Reduce the Cost of Offshore Wind Energy.
- [8] Eugene C. Morgan, Matthew Lackner, Richard M. Vogel, Laurie G. Baise (2011), Probability distributions for offshore wind speeds, Energy Conversion and Management Journal, No. 52, pp. 15-26.
- [9] L.W.M.M. Rademakers, H. Braam (2002), O&M Aspects of the 500MW Offshore Wind Farm at NL7, DOWEC project.`,
    contentHe: `חוות רוח ימיות הן נכסים יקרים, לא רק בהיבטים של תכנון ובנייה, אלא גם בהיבטים של תפעול ותחזוקה. מיקומן המרוחק, יחד עם אילוצי מזג האוויר, הסביבה הימית הקשה והיעדר ציוד גישה מותאם, הופכים את תחזוקתן למסובכת ויקרה בשל עלויות תיקון והובלה גבוהות ואובדן ייצור כואב הנגרם מזמן השבתה רב.

באופן כללי, טכנולוגיית הרוח הימית נמצאת בשלב שבו כדאיותה הכלכלית טרם הוכחה במלואה, ופרויקטים רבים נתמכים במידה רבה בסבסוד ממשלתי [1]. חוסר בשלות זה ניכר, למשל, בבעיות האמינות הרבות הקשורות לרכיבי טורבינות הרוח.

הן ההיבטים המהותיים של תעשיית הרוח הימית והן בעיות האמינות שעמן היא מתמודדת תורמים לעלויות תפעול ותחזוקה (O&M) גבוהות, אשר בסופו של דבר פוגעות בתחרותיות שלה מול מקורות אנרגיה אחרים. מקובל להניח שעד 25% מעלות האנרגיה המיוצרת בטורבינות רוח ימיות נובעת מפעילויות O&M – פי שניים מאשר בהתקנות יבשתיות [2].

מאמר זה מתאר מתודולוגיה לאופטימיזציה של אסטרטגיית התחזוקה של חוות רוח ימיות, במטרה למזער עלויות לאורך מחזור החיים ולמקסם זמינות וביצועים. apmOptimizer, שפותח על ידי BQR הנדסת אמינות [3], הוא כלי תוכנה מתקדם לבניית מודלים, ניתוח אמינות, הערכת עלויות וביצועים, וכן אופטימיזציה של תחזוקה.

לצורך ההדגמה יצרנו מקרה בוחן של חוות רוח טיפוסית, הכולל מודל מפורט המכסה פרמטרים תפעוליים, עלותיים ותחזוקתיים רבים. מודולי האופטימיזציה של apmOptimizer מיושמים אז על מנת לבצע אופטימיזציה של התחזוקה המונעת, הבדיקות התקופתיות, התחזוקה מבוססת המצב ורמות חלקי החילוף. החל מתרחיש בסיס, נבחנים מספר צעדי אופטימיזציה, בהתאם להליך הערכה טיפוסי של ניתוח RAM/LCC: זמינות תפעולית, זמן השבתה תפעולי, עלויות O&M לאורך מחזור החיים והאנרגיה המיוצרת משמשים כמדדים העיקריים. אסטרטגיית התחזוקה האופטימלית מתקבלת מתהליך אופטימיזציה מדויק ולא מסימולציות מונטה קרלו, שיכולות לספק רק הערכה מקורבת לאסטרטגיה שהוזנה על ידי המשתמש.

מקרה הבוחן מראה בבירור שבאמצעות מספר צעדי אופטימיזציה ניתן להגדיל משמעותית את ביצועי חוות הרוח, ולאפשר לעלות האנרגיה המיוצרת להפוך לתחרותית הרבה יותר. נבחנת גם השפעתם של פרמטרי מידול כגון התפלגות הכשל ותהליך ההידרדרות.

## 1. רקע על apmOptimizer

apmOptimizer הוא כלי למידול, ניתוח ואופטימיזציה שנועד להביא את תחזוקת הנכסים למצב אופטימלי, למקסם זמינות ולמזער את עלות הבעלות לאורך מחזור החיים. אלגוריתמי אופטימיזציה מיושמים כדי לזהות את הפתרון האופטימלי מבין כל התוצאות האפשריות, בהתאם לאילוצי הבעיה וליעדיה. apmOptimizer אינו מבוסס על שיטת מונטה קרלו, שדיוק תוצאותיה תלוי במספר הסימולציות המחושבות ובניחוש המוצלח של המשתמש, אלא מבצע חישובים אנליטיים מדויקים מנתוני הקלט, הכוללים את התפלגות קצב הכשל ומודל האמינות (טורי, מקבילי, יתירות בהמתנה, K מתוך N). תהליך האופטימיזציה עצמו אינו מונחה על ידי המשתמש, שכן מרחב הפתרונות האפשריים מבוסס על חישובים מדויקים אלה. הדבר מבטיח שגם פתרונות לא מובנים מאליהם יזוהו.

במקרה בוחן זה משמש apmOptimizer לבניית מודל של חוות רוח טיפוסית ולחישוב פרמטרי האמינות, הזמינות והתחזוקתיות (RAM) שלה, וכן עלויות מחזור החיים (LCC). מחושבים גם הביצועים האנרגטיים של חוות הרוח ומחולצת עלות האנרגיה. מודל apmOptimizer יכול לשלב את המאפיינים הייחודיים ביותר של חוות רוח ושל פעולות התחזוקה שלה: מגבלות נגישות, שונות מזג אוויר, עלות גבוהה של זמן השבתה, תחזוקה מתוכננת ובלתי מתוכננת ועוד. אף שלא נעשה זאת במקרה בוחן זה, ניתן להשתמש גם בנתונים תפעוליים מחוות רוח אמיתית (רישומי תחזוקה, יומן, קריאות חיישנים) להערכה טובה יותר של התפלגות הכשל.

לאחר הגדרת מודל הבסיס ואפיונו, נוצרו מספר תרחישים הבוחנים ברצף את ההשפעה של בדיקות מונעות, החלפות מונעות ורמת המלאי. כל אחד מתרחישים אלה מועבר ל-apmOptimizer לאופטימיזציה, ומדדי RAM/LCC והביצועים מושווים.

## 2. תיאור המודל

היקפו של מקרה בוחן זה מכסה רק סקירה קצרה של המרכיבים העיקריים, ולא תיאור מלא של פרמטרי הקלט. המחברים מבקשים להדגיש כי הנתונים ששימשו בעבודה זו התקבלו ממקורות זמינים לציבור, ונתונים שאינם זמינים הוערכו באמצעות שיקול דעת הנדסי.

### 2.1 מרכיבי חוות הרוח

המערכת הנדונה היא חוות רוח בהספק 240MW, המורכבת מ-80 טורבינות רוח גנריות, כל אחת בהספק נקוב של 3MW, תחנת משנה ימית אחת וכבלים תת-ימיים. הטורבינות מקובצות ל-8 אשכולות (רדיאלים), שכל אחד מכיל 10 טורבינות וכבלים. החווה ממוקמת במרחק ממוצע של 30 ק"מ מהחוף. חוות הרוח פועלת בבסיס 24/7, עם תוחלת חיים צפויה של 20 שנה. מכיוון שמקרה בוחן זה מתמקד בהערכת העלויות הקשורות לפעילויות O&M בלבד, מונח שחוות הרוח פעילה לחלוטין משנה 1 ושלבי ההפעלה והפירוק אינם נכללים בניתוח העלויות.

מונח שכל טורבינת רוח בהספק 3MW מווסתת בזווית הלהבים, בעלת מהירות משתנה, עם תיבת הילוכים מותקנת, וממודלת באמצעות מבנה פירוק המותאם מפרויקט Reliawind [4]. למען הפשטות, עץ הפירוק מוגבל לרמת המכלולים, ותת-מכלולים ורכיבים אינם ממודלים.

### 2.2 פרמטרי כשל ואמינות

קצב הכשל הכולל של טורבינת הרוח הונח כ-3.8 כשלים/טורבינה/שנה, בהתבסס על נתוני בסיס יבשתיים בערך של 1.5 ומקדמי המרה K1=1.75 ו-K2=1.447 עבור עומס סביבתי ומיקום קרוב לחוף בהתאמה [5]. תרומת הרכיבים לקצב הכשל הכולל של טורבינת הרוח התקבלה מ-[6], שם מונחת התפלגות מעריכית.

בהתאם לגישת [7], הגדרנו מספר אופני כשל (FM) גנריים לכל מרכיב של טורבינת הרוח, ולכל אופן כשל יחס כשל (FR). לדוגמה, לתיבת ההילוכים (GB) מוגדרים 3 אופני כשל.

אופני הכשל שיש להם משימות בדיקה מוגדרים כסמויים (אחרים הם אופני כשל גלויים), כלומר לא ניתן לזהות את הכשל עד שמתבצעת בדיקה. כשלים המזוהים על ידי ציוד ניטור מצב נחשבים גלויים. בנוסף, תהליך ההידרדרות של אופני כשל סמויים ממודל על ידי הגדרת "זמן ממוצע מתחילת ההידרדרות ועד לכשל", וכן פרמטר "סטייה" המייצג את אי-הוודאות בתהליך ההידרדרות.

### 2.3 משימות ומשאבי תחזוקה

לאופני הכשל מוקצות משימות תחזוקה ומשאבי תחזוקה הנדרשים לשיקום הציוד בהתאם ל-[7].

עלויות כוח האדם, ציוד התמיכה, החומרים ומשאבים אחרים מוגדרות בספריות ומוקצות למשימות התחזוקה. חוות הרוח מתוחזקת על ידי 20 טכנאים העובדים 12 שעות ביום, 350 ימים בשנה, בעלות של 70 יורו לשעה. צוות התפעול (השוהה בחדר בקרה) מורכב מ-3 צוותים של 3 מפעילים (משמרות של 8 שעות) בעלות של 50 יורו לשעה.

### 2.4 מיקומי תחזוקה

רוב משימות התחזוקה מבוצעות באתר, ורק משימות התיקון הכבדות ביותר כמו תיקון להב או תיבת הילוכים מבוצעות במתקן תחזוקה יבשתי. חלקי החילוף מאוחסנים גם הם במתקן זה, אליו הם מגיעים מספקים שונים או לאחר תיקון. רכש חלקי החילוף מתבצע לפי דרישה, ומוגדר עיכוב זמן המביא בחשבון עיכובי ייצור ו/או מנהלה לכל פריט בר-החלפה. לדוגמה, עיכוב הרכש של הלהבים הוא 6 ימים. מיקומי התחזוקה וההובלה ביניהם מוגדרים ב-apmOptimizer באמצעות מפת התחזוקה.

מוגדרות מספר אוניות גישה בין חוות הרוח לבין מתקן התחזוקה:

- אוניית הנחת כבלים – לכבלים
- אוניית הרמה (Jack-up) – לחלקים גדולים
- אוניית גישה לעובדים (Workboat) – להובלת כוח אדם
- אוניית תמיכה לצלילה – לבדיקת יסודות

טורבינות הרוח מצוידות במנוף פנימי המסוגל לטפל בחלקים קטנים, בעוד חלקים גדולים יותר דורשים שימוש באוניית ההרמה.

אספקת חלקי חילוף למתקן התחזוקה מתבצעת על ידי משאית סטנדרטית בזמן הובלה ממוצע של 20 שעות, למעט הלהבים שעבורם משמשת משאית מיוחדת בזמן הובלה ממוצע של 120 שעות.

### 2.5 פרמטרים סביבתיים

שונות הרוח היא הגורם המשמעותי ביותר בייצור האנרגיה. השונות שלה היא בעיקרה עונתית ונחקרה בהרחבה בספרות המקצועית [8]. במקרה בוחן זה, שונות מהירות הרוח מובאת בחשבון על בסיס שנתי בתוך מודול ייצור האנרגיה, על ידי הנחת פונקציית צפיפות של מהירות הרוח מסוג ויבול, עם פרמטר סקאלה A=8.09, פרמטר צורה k=1.96 [9], ועקומת הספק נקוב של טורבינת Vestas V90 3MW. על ידי שילוב נתונים אלה עם מדדי האמינות של רכיבי חוות הרוח, ניתן לחלץ את סך האנרגיה המיוצרת ברמת חוות הרוח, וכן את עלותה.

חישוב ביצועים ראשוני מניב ייצור אנרגיה שנתי אידיאלי (ללא כשלים) של 960,096 MWh.

ההשפעה המשמעותית השנייה של שונות הרוח היא עיכוב פעולות התחזוקה. הדבר מובא בחשבון במחקר שלנו באמצעות עיכובי זמן הובלה ממוצעים נוספים שנגרמים לאוניות ההובלה.

## 3. תרחיש הבסיס

### 3.1 אסטרטגיית תחזוקה ראשונית

ההנחות הבסיסיות של אסטרטגיית התחזוקה הראשונית מתוארות להלן:

- בדיקת כל הרכיבים מתבצעת פעם בשנה עבור כל הרכיבים.
- כאשר ההידרדרות של פריט שנבדק חמורה מדי או שהוא כשל, מוזמן חלק חילוף מהמלאי.
- אם פריט חילוף זמין במלאי, הוא נשלח לחוות הרוח עם משאבי התחזוקה הנדרשים באמצעות האוניה המתאימה; אם לא, הוא מוזמן מהספק.
- עיכוב מלאי בשל אילוצים מנהליים מונח כ-24 שעות.
- עיכובי הספקים תלויים בפריט (מספר ימים בכל המקרים).
- עיכובי ההובלה כוללים: זמן גיוס, זמן הובלה, זמן מיצוב ועיכוב משוער עקב שונות מזג האוויר.
- כאשר חלק חילוף מגיע לחוות הרוח, הפריט מוסר ומוחלף בחדש.
- הפריט שכשל מוחזר ליבשה לתיקון במתקן התיקון בהתאם למשימות שהוגדרו. מונח עיכוב תיקון (לנהלים מנהליים) של יומיים בנוסף לזמן התיקון.
- הפריט המתוקן מוזן למלאי.
- לחלק מהפריטים יש מגבלת תיקונים, כלומר ניתן לתקנם רק מספר מוגבל של פעמים לפני שהם מסולקים. במקרה זה מוזמן חלק חילוף חדש.

### 3.2 תוצאות הניתוח

מתבצעים חישובים לחילוץ המאפיינים העיקריים של טורבינת הרוח: מדדי אמינות, מדדי ביצועים ומדדי עלות.

מערכות הזווית (pitch) והסיבוב (yaw) הן בבירור התורמות העיקריות לזמן ההשבתה, יחד עם הגנרטור ותיבת ההילוכים. הדבר נובע בעיקר מקצב כשל גבוה יחסית בשילוב עם זמן טיפול ארוך: כאשר חלק זקוק להחלפה, נדרש פרק זמן ארוך עד שאוניית ההרמה תהיה זמינה ותגיע לחוות הרוח, ובינתיים טורבינת הרוח אינה פעילה. מנגד, רכיבים בעלי קצבי כשל דומים, כגון ממירי תדר, תורמים הרבה פחות לזמן ההשבתה מכיוון שחלקי החילוף מובאים לאתר מהר יותר באמצעות אוניות הגישה. בנוסף, המספר המוגבל של חלקי חילוף במלאי גם הוא גורם לזמן השבתה, שכן ייתכן ויידרשו יותר חלקי חילוף לתיקון מכפי שזמינים במלאי, ובכך נוצר זמן המתנה לחלקים.

זמינות טורבינת הרוח המתקבלת היא 80%, והאנרגיה המיוצרת על ידי כל חוות הרוח היא 763,697 MWh/שנה בעלות של 23.4 מיליון יורו (O&M בלבד). עלות האנרגיה המתקבלת היא 31 יורו/MWh מיוצר, ומקדם הקיבולת של חוות הרוח הוא 36.3%.

## 4. תרחישי אופטימיזציה

### 4.1 אופטימיזציה של בדיקות

לוח הבדיקות של תרחיש הבסיס מעניק משקל זהה לכל רכיב בטורבינה. אף שגישה זו אינה חריגה בהתקנות קיימות, היא אינה מוצדקת לחלוטין. לוח בדיקות מותאם אמור להיות מסוגל לשפר את זמינות המערכת על ידי התחשבות בקצבי האמינות ובתהליכי ההידרדרות השונים. מודול אופטימיזציית הבדיקות של apmOptimizer משמש לביצוע האופטימיזציה, כאשר מטרת האופטימיזציה היא מזעור העלויות הכוללות, כלומר עלויות תחזוקה, עלויות נזק מכשל ועלויות זמן השבתה (אובדן הכנסות). באופן אופציונלי ניתן להגדיר זמינות או אמינות מינימלית נדרשת ברמת הרכיב או המערכת. מכיוון שהבדיקות מתוכננות מראש, ניתן להזמין מראש גם את חלקי החילוף הנדרשים ולספקם בזמן.

האופטימיזציה מניבה תוצאות משמעותיות מאוד: זמינות טורבינת הרוח עולה ב-7.3 נקודות, מה שמתורגם לעלייה של 9% בייצור האנרגיה. מנקודת מבט העלויות ההשפעה ניכרת אף יותר, באמצעות הפחתה של 26.5% בעלויות התחזוקה המתקנת, וכן הפחתה בעלויות התחזוקה המונעת, הודות לבדיקות ממוקדות יותר, אף שמבוצעות הרבה יותר בדיקות (עלויות הבדיקה משתנות לפי הציוד). בסך הכול, עלות האנרגיה המיוצרת מופחתת בכ-30%.

היתרון של ביצוע אופטימיזציה באמצעות אלגוריתם אופטימיזציה, לעומת סימולציות מסוג מונטה קרלו, נראה בבירור בבחינת לוח הבדיקות המוצע. אלגוריתם האופטימיזציה חזק מספיק כדי להניב פתרונות מקוריים המספקים את ההפחתות החזקות ביותר בעלויות ואת השיפורים החזקים ביותר בביצועים.

### 4.2 תרחיש מערכת ניטור מצב – אופטימיזציה של תחזוקה מונעת

כאן נבחנת יעילות יישומה של מערכת CMS. מערכות CMS שימושיות במקרה של חוות ימיות, שכן הן מספקות למפעיל זיהוי וזיהוי כשל, ומאפשרות לתזמן תיקון/החלפה בדיוק רב הרבה יותר. עם זאת, מערכות אלה עדיין יקרות ואינן תמיד מספקות תמונה ברורה של מה שמתרחש בפועל בטורבינה.

בתרחיש הנוכחי אנו מניחים ש-CMS מותקנת על הפריטים הבאים: תיבת הילוכים, מערכת זווית ומערכת סיבוב (מובילי זמן ההשבתה העיקריים) ושההידרדרות שלהם נמדדת באופן רציף. בשילוב עם מודל חיזוי משוער, הם מאפשרים לחזות את התפלגות הזמן-עד-כשל (TTF) בנקודת זמן נתונה, ואז להחליט על שיטת תכנון תחזוקה אופטימלית המביאה בחשבון בצורה הטובה ביותר את עלויות התחזוקה ומשימות תחזוקה אחרות.

לצורך ההשוואה, נכללה בחישובי העלות עלות השקעה ממוצעת של 1,200 יורו למערכת CMS (עלות CMS כוללת של 288,000 יורו). אפילו עם עלות נוספת זו, יישום ה-CMS נשאר כדאי ומביא להפחתה בעלויות O&M של יותר מ-3.5 מיליון יורו בשנה לעומת התרחיש הקודם. עם זאת, יש לסייג שיפור זה בכך שפריסת מערכות ה-CMS עלולה להשפיע על אמינות הטורבינה, שכן ה-CMS עלולה אף היא לכשול, ובכך שאנו מניחים ש-100% מההידרדרויות מזוהות בבירור, אף שישנם מקרים שבהם לא ניתן לפרש את האותות בבירור.

### 4.3 אופטימיזציה של רמת חלקי החילוף

אופטימיזציה של רמת המלאי של חלקי החילוף היא שלב חשוב בהפחתת זמן ההשבתה, במיוחד עבור חלקים בעלי זמן אספקה או טיפול ארוך מאוד. לאחר שבוצעה אופטימיזציה של הבדיקות והתחזוקה המונעת, הדרישה לחלקי חילוף משתנה ויש לבצע גם בה אופטימיזציה. לשם כך אנו משתמשים במודול אופטימיזציית חלקי החילוף של apmOptimizer. מטרת אלגוריתם האופטימיזציה היא למזער את העלויות והנזק הכוללים. התוכנה מספקת את כמות חלקי החילוף הראשונית האופטימלית וכן את חלקי החילוף הנדרשים להזמנה במהלך מחזור החיים על מנת לחדש את מלאי החלקים שסולקו.

כתוצאה מאופטימיזציית חלקי החילוף, הזמינות עולה ל-93.6%, וכך גם האנרגיה המיוצרת. ההפחתה בעלויות התחזוקה המתקנת משקפת ירידה באובדן ההכנסות עקב זמן השבתה. עלות האנרגיה המיוצרת יורדת מעט נוסף ל-14 יורו/MWh.

## 5. מסקנות ועבודה עתידית

מקרה בוחן זה הדגים את יכולותיו של apmOptimizer במידול יעיל של חוות רוח ימית, ובהצעת תצורות תחזוקה מקוריות לייצור הפחתות משמעותיות בזמן ההשבתה ובעלויות O&M. החל ממודל בסיס היפותטי אך מייצג, מודולי הבדיקה, התחזוקה המונעת וחלקי החילוף הפחיתו בהדרגה את זמן ההשבתה ושיפרו את סך האנרגיה המיוצרת. הוכח שהכרת אופני הכשל של כל רכיב, ובמיוחד תהליך ההידרדרות הקשור, מאפשרת להגדיר את לוח הבדיקות האופטימלי ולהפחית את זמן ההשבתה הכולל.

הוצדק השימוש במערכות ניטור מצב לזיהוי מוקדם של תהליך ההידרדרות, והוכח שהוא שווה את ההשקעה. יתרה מזו, השימוש בהתפלגויות כשל המחולצות ממדידות באתר הוכח כרווחי לאופטימיזציה של החלפות מונעות.

במקרה בוחן עתידי, ישמשו מודל מפורט יותר של רכיבי טורבינת הרוח וכן נתוני שדה מהתקנות אמיתיות של חוות רוח לחילוץ נתוני אמינות מדויקים. נתוני שדה אלה ישמשו להערכת התפלגויות כשל אמיתיות לכל הרכיבים במקום ההנחות המקובלות.

## 6. מקורות

- [1] European Wind Energy Association (EWEA) (2011), Wind in Our Sails.
- [2] Jannie Sonderkar Nielsen, PhD (2013) Risk-Based Operation and Maintenance of Offshore Wind Turbines, Aalborg University.
- [3] BQR Reliability Engineering Ltd, http://www.bqr.com
- [4] ReliaWind Deliverable D 6.7 (2010), Recommendations from the ReliaWind Consortium for the Standardisation for the Wind Industry of Wind Turbine Reliability Taxonomy, Terminology and Data Collection.
- [5] Alexander Karyotakis (2011) On the Optimisation of Operation and Maintenance Strategies for Offshore Wind Farms, Department of Mechanical Engineering, University College London.
- [6] ReliaWind Deliverable D.1.3 (2010), Report on Wind Turbine Reliability Profiles.
- [7] B. Maples, G. Saur, M. Hand, R. van de Pietermen and T. Obdam – NREL (2013), Installation, Operation, and Maintenance Strategies to Reduce the Cost of Offshore Wind Energy.
- [8] Eugene C. Morgan, Matthew Lackner, Richard M. Vogel, Laurie G. Baise (2011), Probability distributions for offshore wind speeds, Energy Conversion and Management Journal, No. 52, pp. 15-26.
- [9] L.W.M.M. Rademakers, H. Braam (2002), O&M Aspects of the 500MW Offshore Wind Farm at NL7, DOWEC project.`,
  },
  {
    slug: "ic-reliability-prediction-physics-of-failure",
    title:
      "Integrated Circuit Reliability Prediction Based on Physics-of-Failure Models in Conjunction with Field Study",
    titleHe:
      "חיזוי אמינות מעגלים משולבים על בסיס מודלים פיזיקליים של כשל בשילוב מחקר שדה",
    excerpt: `Microelectronics device reliability has been improving with every generation of technology whereas the density of the circuits continues to double approximately every 18 months. We studied field data gathered from a large fleet of mobile communications products that were deployed over a period of 8 years in order to examine the reliability trend in the field. We extrapolated the expected failure rate for a series of microprocessors and found a significant trend whereby the circuit failure rate increases approximately half the rate of the technology, going up by approximately in that same 18 month period.`,
    excerptHe:
      "אמינות התקני מיקרואלקטרוניקה משתפרת עם כל דור טכנולוגי, בעוד צפיפות המעגלים ממשיכה להכפיל את עצמה כל 18 חודשים בקירוב. חקרנו נתוני שדה ממוצר תקשורת נייד לאורך 8 שנים כדי לבחון את מגמת האמינות.",
    category: "design-for-reliability",
    date: "2015-01-14",
    readTime: 14,
    content: `Microelectronics device reliability has been improving with every generation of technology whereas the density of the circuits continues to double approximately every 18 months. We studied field data gathered from a large fleet of mobile communications products that were deployed over a period of 8 years in order to examine the reliability trend in the field. We extrapolated the expected failure rate for a series of microprocessors and found a significant trend whereby the circuit failure rate increases approximately half the rate of the technology, going up by approximately in that same 18 month period.

## 1. Introduction

The continued scaling down of semiconductor feature sizes raises challenges in using and developing electronic circuit reliability predictions. Smaller and faster circuits cause higher current densities, lower voltage tolerances and higher electric fields, which make the devices more vulnerable to early failure. Emerging new generations of electronic devices require improved tools for reliability prediction in order to investigate new manifestations of existing failure mechanisms, such as Negative Bias Temperature Instability (NBTI), Electromigration (EM), Hot Carrier Injection (HCI) and Time Dependent Dielectric Breakdown (TDDB).

Reliability prediction simulations are the most powerful tools developed over the years to cope with these challenging demands. Simulations may provide a wide range of predictions, starting from the lower-level treatment of physics-of-failure (PoF) mechanisms up to high-level simulations of entire devices. Reliability data generated from field failures best represents the electronic circuit reliability in the context of the target system or application. Field failure rates represent competing failure mechanisms' effects and include actual stresses, in contrast to standard industry accelerated life tests.

In this paper, we present a reliability analysis of field failure data recorded from 2002 to 2011 in order to generate real failure rates for various device process technologies and feature sizes (or "technology nodes"). The results of this analysis are used to verify PoF models and a competing failure approach, as implemented in available software tools. Furthermore, we have found that comparing the field failure rates with those obtained from the standard industry High Temperature Operating Life (HTOL) Test reveals the inadequacy of the HTOL to predict integrated circuits' (ICs') failure rates.

## 2. Reliability Modeling and Simulation

### A. History

There has been steady progress over the years in the development of a physics-of-failure understanding of the effects that various stress drivers have on semiconductor structure performance and wearout. This has resulted in better modeling and simulation capabilities. Early investigators sought correlations between the degradation of single device parameters (e.g. Vth, Vdd or Isub) and the degradation of parameters related to circuit performance such as the delay between read and write cycles. It was quickly realized that the degradation of a broad range of parameters describing device performance had to be considered, rather than just a single parameter.

Most of the simulation tools tend to simulate a single failure mechanism such as EM, TDDB, NBTI and HCI. System-level simulators attempting to integrate several mechanisms into a single model have been developed as well. The latest schematic analysis tools, such as fiXtress [20], have integrated reliability simulators. These simulators model the most significant physical failure mechanisms and help designers address the lifetime performance requirements. However, inadequacies, such as complexity in the simulation of large-scale circuits and a lack of prediction of wearout mechanisms, hinder broader adoption of these tools.

### B. Validation Concerns

Reliability simulations are commonly based on a combination of PoF models, empirical data and statistical models developed over the years by different research groups and industries. The inevitable consequence of a wide range of models and approaches is a lack of confidence in the obtained predictions for any given model. From the point of view of a real-world end-user, single failure mechanism modeling and degradation simulations are less meaningful than system level reliability.

Validation and calibration of simulations are both accomplished by comparing simulation predictions with empirical data obtained from lab tests or by analyzing field data. To evaluate the reliability of their devices, semiconductor manufacturers use lab tests such as environment stress screens (ESS), highly accelerated lifetime testing (HALT), HTOL and other accelerated life tests (ALT). Several concerns shed doubt on the prediction accuracy derived from such tests. The assumption that a single failure mechanism will only degrade a circuit is an inaccurate simplification of actual failure dynamics. Furthermore, ALT tests based on sampling a set of devices have the inherent problem of a lack of statistical confidence in the case of zero observed failures. Finally, ALT tests can only mimic actual field conditions to estimate real-world reliability and extrapolation from test environmental stresses to field stresses can be misleading.

## 3. Failure Mechanisms Models

### A. Introduction

The dominant failure mechanisms in Si-based microelectronic devices that are most commonly simulated are EM, TDDB, NBTI and HCI. Other degradation models do exist but are less prevalent. These mechanisms can be generally categorized as Steady State Failure Modes (EM and TDDB) and Wearout Failure Modes (NBTI and HCI). Steady state (random) failure modes are normally considered to be random cases of "stress exceeding strength". The hazard functions generated by random failure modes are constant over time and may produce failures during all bathtub curve stages. On the contrary, the wearout failure modes generate increasing hazard functions and are predominant in later stages of the device life. Wearout failure modes at sub-micron nodes are experienced earlier in the anticipated life of a device, within what was once thought to be dominated only by the steady state failure modes.

### B. Steady State Failure Modes

EM can lead to interconnect failure in an IC. It is characterized by the migration of metal atoms in a conductor along the direction of the electron flow. EM causes opens or voids in some portions of the conductor and corresponding hillocks in other portions. TDDB is caused by the formation of a conducting path through the gate oxide to the substrate due to an electron tunneling current. If the tunneling current is sufficient, it will cause permanent damage to the oxide and surrounding material. This damage will result in performance degradation and eventual failure of the transistors within a device. Core voltages have been scaled down proportionally to feature sizes, but since supply voltages have remained constant, higher electric fields exist at smaller feature sizes. Therefore, field strengths are still a concern since high fields exacerbate the effects of TDDB.

### C. Wearout Failure Modes

NBTI occurs only in pMOS devices stressed with a negative gate bias voltage while at elevated temperatures. Degradation occurs in the gate oxide region allowing electrons and holes to become trapped. Negative bias is driven by smaller electric fields than hot carrier injection, which makes it a more significant threat at smaller technology nodes where increased electric fields are used in conjunction with smaller gate lengths. The interface trap density generated by NBTI is more pronounced with thinner oxides.

HCI occurs in both nMOS and pMOS devices stressed with drain bias voltages. High electric fields energize the carriers (electrons or holes), which are then injected into the gate oxide region. Like NBTI, the degraded gate dielectric can then more readily trap electrons or holes, causing a change in threshold voltage, which in turn results in a shift in the subthreshold leakage current. HCI is accelerated by an increase in bias voltage and is the predominant mechanism at lower stress temperatures. Therefore, hot carrier damage, unlike the other failure mechanisms, will not be replicated in HTOL tests, which are commonly used for accelerated life testing.

## 4. Field Data

### A. Data Source

An extensive field study was conducted in order to demonstrate the accuracy of the simulation tool and verify its prediction capabilities. Reliability predictions were performed based on field failures of DRAMs, microcontrollers and microprocessors.

The field data were extracted from a Motorola database, which encompasses shipments and customers' claims. Unique identifiers of each product and failure enabled the detailed statistical field analysis. The ICs were assembled on boards belonging to a family of communication products shipped during 2002-2009. Component complexity and electrical characteristics were extracted from corresponding component documentation.

As the shipping and failures are recorded continuously, several reliability measurements can be held. The first one is the monthly failure rate, and the second one is the average failure rate, which reflects the overall reliability trend over time. In the specific case where the average failure rate is rather constant over time, we can conclude that the IC is within its useful life period. Traditionally, the exponential distribution is used in this part of life to describe ICs reliability in terms of FIT (one FIT equals one failure per 1E9 hours) as it has great mathematical advantages.

### B. Field Failure Rate Calculation Illustration

The microcontroller is used hereafter to illustrate the process for acquiring environmental information and determining its failure rate based on field data. A total of 96 microcontrollers were replaced during a cumulative total of 595,412 working months.

The average failure rate exhibits a steady state failure rate of approximately 0.02%. We then can calculate a rough estimation for the failure rate to be λ=96/595,412=1.61E-4 Failures/Month, and the mean time to failure to be MTTF=1/λ=6,202 Months. In order to convert the above MTTF into hours, since the microcontroller operates 24 hours a day (730 hours per month), we can roughly estimate the card MTTF as 6,202×730=4,527,612 Hours, which corresponds to 220 FIT.

### C. Weibull Analysis

Each failed IC is assigned to a single product with a unique serial number. Binding the shipment data by the serial number, on one hand, and the failures data, on the other hand, enabled the Weibull analysis. Excellent correlation to the exponential distribution was obtained, with β=1.0266. A null hypothesis of β=1 was tested in order to establish the justification for use of the exponential distribution. A Bonferroni test at confidence level of 95% provided lower and upper limits for β of 0.8758 and 1.203 respectively, with a p-value of 0.746. Thus the exponential distribution can be assumed.

Using the exponential distribution, the MTTF is 141,824 Days. Assuming 24 hours per day, the MTTF is equal to 141,824×24=3,403,776 Hours. This corresponds to 293 FIT with lower and upper confidence limits of 247 and 350 FIT respectively. Weibull analyses for all the analyzed ICs showed similar justification for the use of the exponential distribution.

## 5. Failure Rate vs. Technology

Following the same procedure, we did failure data analysis of the other parts. We find that exponential distribution fits most of the data quite well. This can be explained since all these parts passed burn-in and other mandatory screening tests, and wearout did not yet start.

To reveal the impact of technology scaling on reliability, we first normalized the failure rate to the same area, and then we calculated the ratio of the normalized failure rate of new technology to that of old technology. Based on structure and functionality, all the parts are categorized into three groups: DRAM, processor and micro-controller. It is clear that technology scaling does negatively impact part reliability since all failure rate scaling factors are greater than one. This perception matches also the stress analysis and the effect on reliability models performed by fiXtress [20], a new technology which simulates electronic component stress and optimizes the operating conditions to maximize operation life.

This data is consistent with our observation based on previous technologies: whereby the circuit density increases by about a factor of 2 every 18 months as observed by Moore's law, the reliability of modern systems seems to go approximately at about half the rate of Moore's law on a logarithmic scale, so the system reliability seems to be increasing approximately as the square-root of 2 each 18 months.

## 6. Conclusions & Discussion

A large sample size of field failure data were collected and analyzed to reveal the technology scaling impacts on reliability of complex IC parts. The data includes three types of ICs: DRAM (150nm, 110nm and 100nm), processor (90nm, 65nm and 45nm) and micro-controller (90nm). The earliest data can be dated back to 2002. Through statistical analysis, we find: (1) exponential distribution fits most of the failure data; (2) technology scaling has a negative impact on part reliability by comparing normalized failure rate to area; (3) the failure rate (normalized to area) scaling factor is around 1.4 which is consistent with an increase of FIT that is about half that of Moore's law for integration density.`,
    contentHe: `אמינות התקני מיקרואלקטרוניקה משתפרת עם כל דור טכנולוגי, בעוד צפיפות המעגלים ממשיכה להכפיל את עצמה בקירוב כל 18 חודשים. חקרנו נתוני שדה שנאספו מצי גדול של מוצרי תקשורת ניידת שנפרסו לאורך 8 שנים, על מנת לבחון את מגמת האמינות בשטח. חילצנו את קצב הכשל הצפוי עבור סדרה של מיקרו-מעבדים ומצאנו מגמה משמעותית שבה קצב הכשל של המעגל עולה בקצב של כמחצית מקצב הטכנולוגיה, ועולה בקירוב באותו פרק זמן של 18 חודשים.

## 1. מבוא

ההקטנה המתמשכת של מידות המוליכים למחצה מעלה אתגרים בשימוש ובפיתוח של חיזויי אמינות למעגלים אלקטרוניים. מעגלים קטנים ומהירים יותר גורמים לצפיפויות זרם גבוהות יותר, סבילות מתח נמוכה יותר ושדות חשמליים גבוהים יותר, ההופכים את ההתקנים לפגיעים יותר לכשל מוקדם. דורות חדשים של התקנים אלקטרוניים דורשים כלים משופרים לחיזוי אמינות על מנת לחקור ביטויים חדשים של מנגנוני כשל קיימים, כגון אי-יציבות מתח מוטה שלילי בטמפרטורה (NBTI), נדידה אלקטרונית (EM), הזרקת נשאים חמים (HCI) וקריסת דיאלקטרי תלוית זמן (TDDB).

סימולציות חיזוי אמינות הן הכלים החזקים ביותר שפותחו לאורך השנים כדי להתמודד עם דרישות מאתגרות אלה. סימולציות יכולות לספק מגוון רחב של חיזויים, החל מטיפול ברמה הנמוכה במנגנוני פיזיקת הכשל (PoF) ועד סימולציות ברמה גבוהה של התקנים שלמים. נתוני אמינות הנוצרים מכשלי שדה מייצגים בצורה הטובה ביותר את אמינות המעגל האלקטרוני בהקשר של מערכת או יישום היעד. קצבי כשל בשדה מייצגים את השפעותיהם של מנגנוני כשל מתחרים וכוללים עומסים אמיתיים, בניגוד לבדיקות חיים מואצות תקניות בתעשייה.

במאמר זה אנו מציגים ניתוח אמינות של נתוני כשל בשדה שנרשמו בין 2002 ל-2011, על מנת לייצר קצבי כשל אמיתיים עבור טכנולוגיות תהליך ומידות שונות (או "צמתי טכנולוגיה"). תוצאות ניתוח זה משמשות לאימות מודלי PoF וגישת כשל מתחרה, כפי שמיושמות בכלי תוכנה זמינים. יתרה מזו, מצאנו שהשוואת קצבי הכשל בשדה לאלה המתקבלים מבדיקת אורך החיים בטמפרטורה גבוהה (HTOL) התקנית בתעשייה חושפת את אי-התאמתה של HTOL לחיזוי קצבי הכשל של מעגלים משולבים (ICs).

## 2. מידול וסימולציה של אמינות

### א. היסטוריה

לאורך השנים חלה התקדמות עקבית בפיתוח הבנה של פיזיקת הכשל לגבי ההשפעות שיש לגורמי עומס שונים על ביצועי מבנה המוליך למחצה ועל בלאי. הדבר הביא ליכולות מידול וסימולציה טובות יותר. חוקרים מוקדמים חיפשו מתאמים בין הידרדרות פרמטרים בודדים של ההתקן (למשל Vth, Vdd או Isub) לבין הידרדרות פרמטרים הקשורים לביצועי המעגל, כגון ההשהיה בין מחזורי קריאה לכתיבה. עד מהרה הובן שיש להתחשב בהידרדרות של מגוון רחב של פרמטרים המתארים את ביצועי ההתקן, ולא רק בפרמטר יחיד.

רוב כלי הסימולציה נוטים לדמות מנגנון כשל יחיד כגון EM, TDDB, NBTI ו-HCI. פותחו גם סימולטורים ברמת המערכת המנסים לשלב מספר מנגנונים למודל יחיד. כלי ניתוח הסכמטיקה החדישים ביותר, כגון fiXtress [20], שילבו סימולטורי אמינות. סימולטורים אלה ממדלים את מנגנוני הכשל הפיזיקליים המשמעותיים ביותר ומסייעים למתכננים לעמוד בדרישות הביצועים לאורך החיים. עם זאת, אי-התאמות, כגון מורכבות בסימולציה של מעגלים בקנה מידה גדול והיעדר חיזוי של מנגנוני בלאי, מעכבות את האימוץ הרחב של כלים אלה.

### ב. סוגיות אימות

סימולציות אמינות מבוססות בדרך כלל על שילוב של מודלי PoF, נתונים אמפיריים ומודלים סטטיסטיים שפותחו לאורך השנים על ידי קבוצות מחקר ותעשיות שונות. תוצאה בלתי נמנעת של מגוון רחב של מודלים וגישות היא חוסר אמון בחיזויים המתקבלים עבור כל מודל נתון. מנקודת מבטו של משתמש קצה בעולם האמיתי, מידול מנגנון כשל יחיד וסימולציות הידרדרות פחות משמעותיים מאמינות ברמת המערכת.

אימות וכיול של סימולציות מושגים שניהם באמצעות השוואת חיזויי הסימולציה עם נתונים אמפיריים המתקבלים מבדיקות מעבדה או מניתוח נתוני שדה. כדי להעריך את אמינות התקניהם, יצרני מוליכים למחצה משתמשים בבדיקות מעבדה כגון סינון עומס סביבתי (ESS), בדיקות אורך חיים מואצות מאוד (HALT), HTOL ובדיקות חיים מואצות אחרות (ALT). מספר חששות מטילים ספק בדיוק החיזוי הנגזר מבדיקות כאלה. ההנחה שמנגנון כשל יחיד בלבד יְדַרדֵר מעגל היא פישוט בלתי מדויק של דינמיקת הכשל בפועל. יתרה מזו, לבדיקות ALT המבוססות על דגימה של קבוצת התקנים יש בעיה מובנית של היעדר ביטחון סטטיסטי במקרה של אפס כשלים שנצפו. לבסוף, בדיקות ALT יכולות רק לחקות תנאי שדה אמיתיים כדי להעריך אמינות בעולם האמיתי, וההסקה מעומסי הבדיקה הסביבתיים לעומסי השדה עלולה להיות מטעה.

## 3. מודלים של מנגנוני כשל

### א. מבוא

מנגנוני הכשל הדומיננטיים בהתקני מיקרואלקטרוניקה מבוססי סיליקון המדומים בתדירות הגבוהה ביותר הם EM, TDDB, NBTI ו-HCI. קיימים מודלי הידרדרות נוספים אך הם נפוצים פחות. ניתן לסווג מנגנונים אלה באופן כללי לאופני כשל במצב יציב (EM ו-TDDB) ולאופני כשל מבלאי (NBTI ו-HCI). אופני כשל במצב יציב (אקראיים) נחשבים בדרך כלל למקרים אקראיים של "עומס העולה על חוזק". פונקציות הסיכון הנוצרות מאופני כשל אקראיים קבועות לאורך זמן ועשויות להפיק כשלים בכל שלבי עקומת האמבטיה. לעומת זאת, אופני כשל מבלאי מייצרים פונקציות סיכון עולות ושולטים בשלבים מאוחרים יותר של חיי ההתקן. אופני כשל מבלאי בצמתים תת-מיקרוניים מתרחשים מוקדם יותר בחיים הצפויים של ההתקן, בתוך מה שפעם נחשב כנשלט רק על ידי אופני הכשל במצב יציב.

### ב. אופני כשל במצב יציב

EM עלולה להוביל לכשל חיבורים במעגל משולב. היא מאופיינת בנדידת אטומי מתכת במוליך לאורך כיוון זרימת האלקטרונים. EM גורמת לחללים או נתקים בחלקים מסוימים של המוליך ולגבעולים מתאימים בחלקים אחרים. TDDB נגרמת מהיווצרות מסלול מוליך דרך תחמוצת השער אל המצע עקב זרם מנהור אלקטרונים. אם זרם המנהור מספיק, הוא יגרום נזק קבוע לתחמוצת ולחומר הסובב. נזק זה יביא להידרדרות בביצועים ולכשל סופי של הטרנזיסטורים בתוך ההתקן. מתחי הליבה הוקטנו ביחס למידות, אך מכיוון שמתחי האספקה נותרו קבועים, קיימים שדות חשמליים גבוהים יותר במידות קטנות יותר. לכן, עוצמות השדה עדיין מהוות חשש, שכן שדות גבוהים מחמירים את השפעות ה-TDDB.

### ג. אופני כשל מבלאי

NBTI מתרחש רק בהתקני pMOS המופעלים במתח שער מוטה שלילי בטמפרטורות גבוהות. ההידרדרות מתרחשת באזור תחמוצת השער ומאפשרת לאלקטרונים ולחורים להילכד. ההטיה השלילית מונעת על ידי שדות חשמליים קטנים יותר מהזרקת נשאים חמים, מה שהופך אותה לאיום משמעותי יותר בצמתי טכנולוגיה קטנים יותר, שבהם נעשה שימוש בשדות חשמליים מוגברים בשילוב עם אורכי שער קטנים יותר. צפיפות מלכודות הממשק הנוצרת על ידי NBTI בולטת יותר עם תחמוצות דקות יותר.

HCI מתרחש בהתקני nMOS ו-pMOS כאחד המופעלים במתחי מוצא (drain). שדות חשמליים גבוהים מעניקים אנרגיה לנשאים (אלקטרונים או חורים), המוזרקים אז לאזור תחמוצת השער. בדומה ל-NBTI, הדיאלקטרי המידרדר של השער יכול אז ללכוד ביתר קלות אלקטרונים או חורים, ולגרום לשינוי במתח הסף, אשר בתורו מביא להיסט בזרם הדליפה התת-סִפִּי. HCI מואץ על ידי עלייה במתח ההטיה והוא המנגנון השולט בטמפרטורות עומס נמוכות יותר. לכן, נזק נשאים חמים, בניגוד למנגנוני הכשל האחרים, לא ישוחזר בבדיקות HTOL, המשמשות בדרך כלל לבדיקות חיים מואצות.

## 4. נתוני שדה

### א. מקור הנתונים

נערך מחקר שדה נרחב על מנת להדגים את דיוק כלי הסימולציה ולאמת את יכולות החיזוי שלו. חיזויי אמינות בוצעו על בסיס כשלי שדה של זיכרונות DRAM, מיקרו-בקרים ומיקרו-מעבדים.

נתוני השדה חולצו ממסד נתונים של מוטורולה, המקיף משלוחים ותביעות לקוחות. מזהים ייחודיים של כל מוצר וכשל אפשרו את ניתוח השדה הסטטיסטי המפורט. המעגלים המשולבים הורכבו על כרטיסים השייכים למשפחה של מוצרי תקשורת שנשלחו במהלך 2002-2009. מורכבות הרכיבים ומאפייניהם החשמליים חולצו מתיעוד הרכיבים המתאים.

מכיוון שהמשלוחים והכשלים נרשמים באופן רציף, ניתן לבצע מספר מדידות אמינות. הראשונה היא קצב הכשל החודשי, והשנייה היא קצב הכשל הממוצע, המשקף את מגמת האמינות הכוללת לאורך זמן. במקרה הספציפי שבו קצב הכשל הממוצע קבוע למדי לאורך זמן, ניתן להסיק שהמעגל המשולב נמצא בתקופת החיים השימושיים שלו. באופן מסורתי, ההתפלגות המעריכית משמשת בחלק זה של החיים לתיאור אמינות מעגלים משולבים במונחי FIT (FIT אחד שווה לכשל אחד ל-1E9 שעות), שכן יש לה יתרונות מתמטיים גדולים.

### ב. הדגמת חישוב קצב הכשל בשדה

המיקרו-בקר משמש להלן להמחשת התהליך לרכישת מידע סביבתי וקביעת קצב הכשל שלו על בסיס נתוני שדה. סך הכול 96 מיקרו-בקרים הוחלפו במהלך סך מצטבר של 595,412 חודשי עבודה.

קצב הכשל הממוצע מציג קצב כשל במצב יציב של כ-0.02%. אז ניתן לחשב הערכה גסה לקצב הכשל של λ=96/595,412=1.61E-4 כשלים/חודש, ואת הזמן הממוצע עד לכשל של MTTF=1/λ=6,202 חודשים. על מנת להמיר את ה-MTTF שלעיל לשעות, מכיוון שהמיקרו-בקר פועל 24 שעות ביממה (730 שעות בחודש), ניתן להעריך באופן גס את MTTF של הכרטיס כ-6,202×730=4,527,612 שעות, המתאים ל-220 FIT.

### ג. ניתוח ויבול

כל מעגל משולב שכשל משויך למוצר יחיד עם מספר סידורי ייחודי. קישור נתוני המשלוח לפי המספר הסידורי, מצד אחד, ונתוני הכשלים, מצד שני, אפשר את ניתוח ויבול. התקבל מתאם מצוין להתפלגות המעריכית, עם β=1.0266. נבדקה השערת אפס של β=1 על מנת לבסס את ההצדקה לשימוש בהתפלגות המעריכית. מבחן בונפרוני ברמת ביטחון של 95% סיפק גבולות תחתון ועליון ל-β של 0.8758 ו-1.203 בהתאמה, עם ערך p של 0.746. לפיכך ניתן להניח את ההתפלגות המעריכית.

בשימוש בהתפלגות המעריכית, ה-MTTF הוא 141,824 ימים. בהנחה של 24 שעות ביום, ה-MTTF שווה ל-141,824×24=3,403,776 שעות. הדבר מתאים ל-293 FIT עם גבולות ביטחון תחתון ועליון של 247 ו-350 FIT בהתאמה. ניתוחי ויבול עבור כל המעגלים המשולבים שנותחו הראו הצדקה דומה לשימוש בהתפלגות המעריכית.

## 5. קצב כשל לעומת טכנולוגיה

בהתאם לאותו הליך, ביצענו ניתוח נתוני כשל של החלקים האחרים. אנו מוצאים שההתפלגות המעריכית מתאימה לרוב הנתונים היטב למדי. ניתן להסביר זאת מכיוון שכל החלקים הללו עברו burn-in ובדיקות סינון מחייבות אחרות, והבלאי טרם החל.

על מנת לחשוף את השפעת קנה המידה הטכנולוגי על האמינות, תחילה נרמלנו את קצב הכשל לאותו שטח, ולאחר מכן חישבנו את היחס בין קצב הכשל המנורמל של הטכנולוגיה החדשה לזה של הטכנולוגיה הישנה. בהתבסס על מבנה ותפקודיות, כל החלקים מסווגים לשלוש קבוצות: DRAM, מעבד ומיקרו-בקר. ברור שקנה המידה הטכנולוגי אכן משפיע לרעה על אמינות החלק, שכן כל מקדמי קנה המידה של קצב הכשל גדולים מאחד. תפיסה זו תואמת גם את ניתוח העומס ואת ההשפעה על מודלי האמינות שבוצעו על ידי fiXtress [20], טכנולוגיה חדשה המדמה את עומס הרכיב האלקטרוני ומבצעת אופטימיזציה של תנאי ההפעלה למיקסום אורך חיי ההפעלה.

נתון זה עקבי עם התצפית שלנו על בסיס טכנולוגיות קודמות: בעוד צפיפות המעגל עולה בערך פי 2 כל 18 חודשים כפי שנצפה בחוק מור, אמינות המערכות המודרניות נראית כעולה בערך במחצית מקצב חוק מור בסקאלה לוגריתמית, כך שאמינות המערכת נראית עולה בקירוב כשורש 2 כל 18 חודשים.

## 6. מסקנות ודיון

נאסף ונותח מדגם גדול של נתוני כשל בשדה כדי לחשוף את השפעות קנה המידה הטכנולוגי על אמינותם של חלקי IC מורכבים. הנתונים כוללים שלושה סוגי מעגלים משולבים: DRAM (150nm, 110nm ו-100nm), מעבד (90nm, 65nm ו-45nm) ומיקרו-בקר (90nm). הנתונים המוקדמים ביותר מתוארכים ל-2002. באמצעות ניתוח סטטיסטי אנו מוצאים: (1) ההתפלגות המעריכית מתאימה לרוב נתוני הכשל; (2) לקנה המידה הטכנולוגי השפעה שלילית על אמינות החלק בהשוואת קצב הכשל המנורמל לשטח; (3) מקדם קנה המידה של קצב הכשל (מנורמל לשטח) הוא סביב 1.4, העקבי עם עלייה ב-FIT שהיא כמחצית מזו של חוק מור עבור צפיפות שילוב.`,
  },
  {
    slug: "mechanical-reliability-simulation",
    title: "Mechanical Reliability Simulation",
    titleHe: "סימולציית אמינות מכנית",
    excerpt: `Today's market requires rapid product development cycle and increasing emphasis on reduced cost and time to market. Advanced simulation methodologies are now routinely used to predict the behavior and response of complex systems as a means of reducing testing. The MRS assists designers to assess reliability performance during system development to achieve a competitive product with high performance.`,
    excerptHe:
      "השוק של היום דורש מחזור פיתוח מוצר מהיר ודגש גובר על הפחתת עלות וזמן לשוק. מתודולוגיות סימולציה מתקדמות משמשות כיום באופן שגרתי לחיזוי התנהגות מערכות מורכבות. MRS מסייע למתכננים להעריך ביצועי אמינות בשלב הפיתוח.",
    category: "reliability-safety",
    date: "2014-10-28",
    readTime: 5,
    content: `Today's market requires rapid product development cycle and increasing emphasis on reduced cost and time to market. Advanced simulation methodologies are now routinely used to predict the behavior and response of complex systems as a means of reducing testing. The MRS assists designers to assess reliability performance during system development to achieve a competitive product with high performance. MRS is a unique modeling and simulation tool, designed to address the root cause failure and reliability prediction of mechanical systems.

Reliability prediction of mechanical systems is very sensitive to material types, loading, friction, forces, corrosion, vibration etc. Failure data, which relies only on operating time, is inadequate to predict the reliability of a mechanical system. Failure rates of mechanical systems cannot usually be described by a persistent failure rate distribution. In addition, a constant failure rate distribution cannot be specified for generic use. Therefore, estimating the reliability of mechanical equipment is a difficult task to perform in the design phase.

Unlike other mechanical reliability prediction models, the MRS model considers dependencies between the mechanical sub-elements, different failure modes, different operating limits and more. The MRS is an analytic prediction and probabilistic method with generic failure models that incorporate reliability into the design process, establishing a scientific basis for evaluating mechanical stress margins, potential failure mechanisms, relevant geometry, operating loads, environmental parameters, structure, corrosion, dimension and fatigue.

## How MRS Works

The Mechanical Reliability Simulation (MRS) module is a tool that performs fast analytic reliability predictions for any type of mechanical system. MRS analyzes a mechanical system containing elements and subsystems. Each element includes a number of input parameters. These input parameters (geometry, material properties, loads, environment, etc.) are defined in the element dialog box.

The variations of these input parameters are defined as random input variables and are characterized by their distribution type (Gaussian, Normal, Log-normal, Exponential, Uniform, Weibull, Pareto, Rayleigh) and by their distribution parameters (mean values, standard deviation, etc.). The times of failure for each element are calculated at random (using Monte Carlo simulation). The calculation model includes coupled time-dependent failure modes: wear, fatigue, corrosion, and creep.

After the calculation of massive randomly-generated times to failure, MRS automatically creates a time-to-failure histogram, and calculates parameters for all possible distribution types. After this, the program selects the optimal distribution type. For this, the program takes all standard distributions and examines, using a Chi-squared (χ²) test, their compliance with the observed data. The distribution with the greatest significance level is highlighted in the distribution grid and the corresponding failure density chart is shown.`,
    contentHe: `השוק של היום דורש מחזור פיתוח מוצר מהיר ודגש גובר על הפחתת עלות וזמן הגעה לשוק. מתודולוגיות סימולציה מתקדמות משמשות כיום באופן שגרתי לחיזוי ההתנהגות והתגובה של מערכות מורכבות כאמצעי להפחתת בדיקות. ה-MRS מסייע למתכננים להעריך ביצועי אמינות במהלך פיתוח המערכת על מנת להשיג מוצר תחרותי בעל ביצועים גבוהים. MRS הוא כלי מידול וסימולציה ייחודי, שנועד לטפל בכשל שורש ובחיזוי אמינות של מערכות מכניות.

חיזוי אמינות של מערכות מכניות רגיש מאוד לסוגי חומרים, עומסים, חיכוך, כוחות, קורוזיה, רעידות וכדומה. נתוני כשל, המסתמכים רק על זמן הפעלה, אינם מספיקים לחיזוי אמינותה של מערכת מכנית. בדרך כלל לא ניתן לתאר את קצבי הכשל של מערכות מכניות באמצעות התפלגות קצב כשל קבועה. בנוסף, לא ניתן לציין התפלגות קצב כשל קבועה לשימוש גנרי. לפיכך, הערכת אמינותו של ציוד מכני היא משימה קשה לביצוע בשלב התכנון.

בניגוד למודלים אחרים לחיזוי אמינות מכנית, מודל ה-MRS מתחשב בתלות בין תת-המרכיבים המכניים, באופני כשל שונים, בגבולות הפעלה שונים ועוד. ה-MRS הוא שיטת חיזוי אנליטית והסתברותית עם מודלי כשל גנריים המשלבים אמינות בתהליך התכנון, ומבססים בסיס מדעי להערכת מרווחי עומס מכניים, מנגנוני כשל אפשריים, גאומטריה רלוונטית, עומסי הפעלה, פרמטרים סביבתיים, מבנה, קורוזיה, מימדים ועייפות.

## כיצד MRS פועל

מודול סימולציית האמינות המכנית (MRS) הוא כלי המבצע חיזויי אמינות אנליטיים מהירים לכל סוג של מערכת מכנית. MRS מנתח מערכת מכנית המכילה מרכיבים ותת-מערכות. כל מרכיב כולל מספר פרמטרי קלט. פרמטרי קלט אלה (גאומטריה, תכונות חומר, עומסים, סביבה וכדומה) מוגדרים בתיבת הדו-שיח של המרכיב.

השונות של פרמטרי קלט אלה מוגדרת כמשתני קלט אקראיים ומאופיינת לפי סוג ההתפלגות שלהם (גאוס, נורמלי, לוג-נורמלי, מעריכי, אחיד, ויבול, פארטו, ריילי) ולפי פרמטרי ההתפלגות שלהם (ערכים ממוצעים, סטיית תקן וכדומה). זמני הכשל לכל מרכיב מחושבים באקראי (באמצעות סימולציית מונטה קרלו). מודל החישוב כולל אופני כשל מצומדים תלויי זמן: בלאי, עייפות, קורוזיה וזחילה.

לאחר חישוב כמות עצומה של זמני כשל שנוצרו באקראי, MRS יוצר באופן אוטומטי היסטוגרמת זמן-עד-כשל, ומחשב פרמטרים עבור כל סוגי ההתפלגות האפשריים. לאחר מכן, התוכנה בוחרת את סוג ההתפלגות האופטימלי. לשם כך, התוכנה לוקחת את כל ההתפלגויות הסטנדרטיות ובוחנת, באמצעות מבחן כי-בריבוע (χ²), את התאמתן לנתונים שנצפו. ההתפלגות בעלת רמת המובהקות הגבוהה ביותר מודגשת ברשת ההתפלגויות, ומוצג תרשים צפיפות הכשל המתאים.`,
  },
];

export function getArticlesByCategory(category: Category): Article[] {
  return articles.filter((a) => a.category === category);
}

export function getFeaturedArticle(): Article | undefined {
  return articles.find((a) => a.featured) ?? articles[0];
}

export function getRecentArticles(count = 3): Article[] {
  return [...articles]
    .sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime())
    .slice(0, count);
}

export function getArticleBySlug(slug: string): Article | undefined {
  return articles.find((a) => a.slug === slug);
}

export function formatDate(dateStr: string, locale: "en" | "he" = "en"): string {
  const date = new Date(dateStr);
  return date.toLocaleDateString(locale === "he" ? "he-IL" : "en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });
}
