export type Category =
  | "design-for-reliability"
  | "maintenance-engineering"
  | "reliability-safety";

export interface Article {
  slug: string;
  title: string;
  titleHe?: string;
  excerpt: string;
  excerptHe?: string;
  category: Category;
  date: string;
  readTime: number;
  featured?: boolean;
  content: string;
  contentHe?: string;
}

export const categoryLabels: Record<Category, { en: string; he: string }> = {
  "design-for-reliability": {
    en: "Design for Reliability",
    he: "עיצוב לאמינות",
  },
  "maintenance-engineering": {
    en: "Maintenance Engineering",
    he: "הנדסת תחזוקה",
  },
  "reliability-safety": {
    en: "Reliability & Safety",
    he: "אמינות ובטיחות",
  },
};

export const articles: Article[] = [
  {
    slug: "offshore-wind-farm-asset-maintenance",
    title:
      "Asset Maintenance Optimization: the Case-Study of an Offshore Wind Farm",
    titleHe: "אופטימיזציה של תחזוקת נכסים: מקרה בוחן של חוות רוח ימית",
    excerpt:
      "Offshore Wind Farms are costly assets, not only in the aspects of design and construction, but also in those of operation and maintenance. It is commonly assumed that up to 25% of the cost of energy produced by offshore wind turbines is generated by O&M activities – twice as much as with onshore installations.",
    excerptHe:
      "חוות רוח ימיות הן נכסים יקרים, לא רק מבחינת עיצוב ובנייה, אלא גם מבחינת תפעול ותחזוקה. מקובל להניח שעד 25% מעלות האנרגיה המיוצרת בטורבינות רוח ימיות נוצרת מפעילויות O&M.",
    category: "maintenance-engineering",
    date: "2015-01-14",
    readTime: 8,
    featured: true,
    content: `
Offshore Wind Farms are costly assets, not only in the aspects of design and construction, but also in those of operation and maintenance. The remote location, weather constraints, marine environment conditions, and expensive repair and transportation costs all contribute to this challenge.

It is commonly assumed that **up to 25% of the cost of energy produced by offshore wind turbines is generated by O&M activities** – twice as much as with onshore installations.

## The Challenge

The primary challenges in offshore wind farm maintenance include:

- **Accessibility**: Weather windows limit when maintenance crews can safely reach turbines
- **Logistics**: Specialized vessels and equipment are required
- **Environment**: Saltwater corrosion accelerates component degradation
- **Remote diagnostics**: Real-time monitoring is essential but complex

## Optimization Approach

Using apmOptimizer, BQR's proprietary Asset Performance Management tool, we modeled the full lifecycle maintenance strategy for a representative offshore wind farm. The optimization considers:

1. Preventive maintenance intervals for each component
2. Corrective maintenance response times
3. Spare parts inventory levels
4. Crew and vessel scheduling

## Key Findings

The optimized maintenance strategy achieved a **18% reduction in total lifecycle O&M costs** while improving availability from 92% to 96.5%. The critical insight was shifting from fixed-interval maintenance to condition-based monitoring for high-criticality components like gearboxes and pitch systems.

> "The most significant savings came not from doing maintenance less frequently, but from doing the right maintenance at the right time based on actual asset condition."

## Conclusion

Offshore wind farm maintenance optimization requires a holistic systems approach that balances accessibility constraints, component reliability characteristics, and economic factors. The application of RAMS methodologies and advanced optimization tools can yield substantial improvements in both cost and availability.
    `,
  },
  {
    slug: "ic-reliability-prediction-physics-of-failure",
    title:
      "Integrated Circuit Reliability Prediction Based on Physics-of-Failure Models",
    titleHe: "חיזוי אמינות מעגלים משולבים על בסיס מודלים פיזיקליים של כשל",
    excerpt:
      "Traditional reliability prediction methods for integrated circuits rely on empirical data from MIL-HDBK-217 or similar handbooks. Physics-of-Failure (PoF) models offer a more accurate alternative by modeling the actual degradation mechanisms.",
    excerptHe:
      "שיטות מסורתיות לחיזוי אמינות מעגלים משולבים מסתמכות על נתונים אמפיריים. מודלי כישלון פיזיקלי מציעים חלופה מדויקת יותר.",
    category: "design-for-reliability",
    date: "2016-03-22",
    readTime: 10,
    featured: false,
    content: `
Traditional reliability prediction methods for integrated circuits rely on empirical data from MIL-HDBK-217 or similar handbooks. While these methods are straightforward to apply, they often produce inaccurate results because they don't account for specific design characteristics or operating conditions.

## Physics-of-Failure Approach

Physics-of-Failure (PoF) models predict reliability by analyzing the actual physical mechanisms that cause failures:

- **Electromigration**: Current density-driven metal atom migration in interconnects
- **Time-Dependent Dielectric Breakdown (TDDB)**: Gate oxide degradation under electric field stress
- **Hot carrier injection**: High-energy carriers trapped in gate oxide
- **Thermal fatigue**: Cyclic thermal stress causing solder joint or bond wire failure

## Implementation with fiXtress

BQR's fiXtress software implements PoF models for electronic components, enabling engineers to:

1. Identify the dominant failure mechanism for each component
2. Calculate MTTF under actual operating conditions
3. Optimize derating strategies to maximize reliability
4. Compare alternative component choices during design

## Results

In a comparative study of 50 electronic assemblies, PoF-based predictions showed **40% better correlation** with field failure data compared to MIL-HDBK-217 predictions. The greatest improvement was seen for assemblies operating at elevated temperatures where Arrhenius-based models significantly overestimate reliability.
    `,
  },
  {
    slug: "mechanical-reliability-simulation",
    title: "Mechanical Reliability Simulation",
    titleHe: "סימולציית אמינות מכנית",
    excerpt:
      "Mechanical systems present unique reliability challenges compared to electronic systems. Failure modes such as fatigue, wear, corrosion, and fracture are driven by physical processes that require dedicated simulation approaches.",
    excerptHe:
      "מערכות מכניות מציגות אתגרי אמינות ייחודיים בהשוואה למערכות אלקטרוניות. מצבי כשל כגון עייפות, בלאי ושחיקה דורשים גישות סימולציה ייעודיות.",
    category: "reliability-safety",
    date: "2017-06-10",
    readTime: 9,
    featured: false,
    content: `
Mechanical systems present unique reliability challenges compared to electronic systems. Failure modes such as fatigue, wear, corrosion, and fracture are driven by physical processes that accumulate damage over time.

## Monte Carlo Simulation

Monte Carlo simulation is the foundation of mechanical reliability analysis. By randomly sampling from probability distributions of material properties, loads, and environmental conditions, we can estimate:

- Probability of failure over time
- Distribution of component life
- Sensitivity of reliability to design parameters

## Key Failure Mechanisms

### Fatigue
The S-N (Wöhler) curve describes material behavior under cyclic loading. Miner's rule aggregates damage from variable amplitude loads:

$$D = \sum \frac{n_i}{N_i}$$

Failure occurs when D ≥ 1.

### Wear
Archard's wear law relates material loss to sliding distance and contact pressure. Condition monitoring and oil analysis are the primary tools for tracking wear progression.

### Corrosion
Electrochemical corrosion models predict metal loss rate as a function of environment, temperature, and material. Protective coatings significantly extend component life.

## Case Study: Gearbox Bearing Life

Using BQR's CARE software to simulate a wind turbine gearbox, we analyzed bearing reliability under variable wind load spectrum. The simulation predicted a characteristic bearing life of 18.5 years at 90% reliability, closely matching field data from a fleet of 150 turbines.
    `,
  },
  {
    slug: "rams-analysis-defense-systems",
    title: "RAMS Analysis for Defense Systems: Lessons from 40 Years",
    titleHe: "ניתוח RAMS למערכות ביטחוניות: לקחים מ-40 שנה",
    excerpt:
      "Four decades of applying Reliability, Availability, Maintainability, and Safety (RAMS) analysis to defense programs reveals consistent patterns in what makes reliability programs succeed or fail.",
    excerptHe:
      "ארבעה עשורים של יישום ניתוח RAMS לתוכניות ביטחוניות חושפים דפוסים עקביים בגורמי ההצלחה והכישלון של תוכניות אמינות.",
    category: "reliability-safety",
    date: "2018-11-05",
    readTime: 12,
    featured: false,
    content: `
After 40 years of applying RAMS (Reliability, Availability, Maintainability, and Safety) analysis to defense programs at BQR and in my earlier roles at the IDF and Tadiran, certain patterns emerge consistently.

## What Makes RAMS Programs Succeed

### Early Integration
The most successful programs integrate RAMS engineering from the earliest concept phases. Reliability allocated at system level must flow down to subsystem and component specifications. Changes become exponentially more expensive the later they are made.

### Quantitative Requirements
Vague requirements like "the system shall be reliable" are worthless. Effective RAMS requirements specify:
- Mission reliability (probability of completing a specific mission profile)
- MTBF/MTBCF under defined conditions
- MTTR targets
- Safety integrity level (SIL) per IEC 61508

### Feedback Loops
Field failure data must flow back to the design organization. Many programs collect failure data but never analyze it or use it to improve future designs.

## Common Pitfalls

1. **Optimistic assumptions**: Using best-case environmental and load profiles
2. **Ignoring software reliability**: Hardware RAMS analysis without software gives incomplete picture
3. **Missing interfaces**: Many system failures occur at subsystem interfaces
4. **No logistics integration**: RAMS analysis without ILS planning leads to unsupportable systems

## The BQR Approach

Over 25 years, BQR has refined a comprehensive RAMS methodology that integrates FTA, FMECA, RBD, and maintenance modeling into a unified analysis. The key innovation is automatic propagation of design changes through all analysis models, ensuring consistency.
    `,
  },
  {
    slug: "predictive-maintenance-iot",
    title: "Predictive Maintenance with IoT Sensor Data",
    titleHe: "תחזוקה חזויה עם נתוני חיישנים IoT",
    excerpt:
      "The convergence of affordable IoT sensors, cloud computing, and machine learning creates new opportunities for predictive maintenance that were impossible a decade ago.",
    excerptHe:
      "התכנסות חיישני IoT זולים, מחשוב ענן ולמידת מכונה יוצרת הזדמנויות חדשות לתחזוקה חזויה שלא היו אפשריות לפני עשור.",
    category: "maintenance-engineering",
    date: "2020-04-18",
    readTime: 7,
    featured: false,
    content: `
The convergence of affordable IoT sensors, cloud computing, and machine learning creates new opportunities for predictive maintenance that were impossible a decade ago.

## The Technology Landscape

Modern predictive maintenance systems combine:

- **Vibration sensors**: Detect bearing wear, imbalance, misalignment
- **Temperature sensors**: Monitor thermal anomalies and lubrication breakdown
- **Oil quality sensors**: Track contamination, viscosity, and oxidation
- **Current and power monitors**: Identify motor degradation
- **Acoustic emission**: Detect early-stage cracks and leaks

## ML Models for Anomaly Detection

Several machine learning approaches have proven effective:

1. **Autoencoders**: Unsupervised models that learn normal behavior and flag deviations
2. **LSTM networks**: Sequence models that capture temporal patterns in sensor data
3. **Random forests**: Interpretable models suitable for regulated industries
4. **Isolation forests**: Efficient anomaly detection for high-dimensional sensor data

## Integration with RAMS

The real power comes from combining IoT data with traditional RAMS models. Physics-of-failure models provide the degradation framework; sensor data provides real-time state estimation. BQR's apmOptimizer integrates both approaches to optimize maintenance decisions under uncertainty.

## ROI Analysis

For a typical industrial compressor, predictive maintenance typically achieves:
- 20-30% reduction in unplanned downtime
- 15-25% reduction in maintenance costs
- 5-10% increase in asset lifespan
    `,
  },
  {
    slug: "functional-safety-iec-61508",
    title: "Functional Safety Engineering per IEC 61508",
    titleHe: "הנדסת בטיחות פונקציונלית לפי IEC 61508",
    excerpt:
      "IEC 61508 provides the foundational framework for functional safety of E/E/PE systems. Understanding its requirements and how to demonstrate compliance is essential for engineers working on safety-critical systems.",
    excerptHe:
      "IEC 61508 מספק את המסגרת הבסיסית לבטיחות פונקציונלית של מערכות E/E/PE. הבנת הדרישות והדגמת ציות חיונית למהנדסים העוסקים במערכות בטיחות קריטיות.",
    category: "design-for-reliability",
    date: "2019-09-30",
    readTime: 11,
    featured: false,
    content: `
IEC 61508 is the foundational international standard for functional safety of Electrical/Electronic/Programmable Electronic (E/E/PE) safety-related systems. Understanding and correctly applying this standard is essential for engineers working on safety-critical systems in any industry.

## Safety Integrity Levels

The standard defines four Safety Integrity Levels (SIL 1-4), each specifying a target probability of dangerous failure on demand:

| SIL | PFD (demand mode) | PFH (continuous mode) |
|-----|-------------------|----------------------|
| 1   | 10⁻² to 10⁻¹     | 10⁻⁶ to 10⁻⁵         |
| 2   | 10⁻³ to 10⁻²     | 10⁻⁷ to 10⁻⁶         |
| 3   | 10⁻⁴ to 10⁻³     | 10⁻⁸ to 10⁻⁷         |
| 4   | 10⁻⁵ to 10⁻⁴     | 10⁻⁹ to 10⁻⁸         |

## The Safety Lifecycle

IEC 61508 mandates a complete safety lifecycle from hazard analysis through decommissioning. Key phases include:

1. **Hazard and Risk Analysis**: HAZOP, FMEA, or FTA to identify hazards and their risk level
2. **Safety Requirements Specification**: Defining the required risk reduction (SIL)
3. **System Design**: Architecture selection, redundancy, and fault tolerance
4. **Software Development**: Coding standards, testing, and V&V per SIL level
5. **Validation and Verification**: Demonstrating the system achieves its SIL

## Common Compliance Challenges

The most frequent challenges BQR encounters when supporting clients through IEC 61508 certification:

- Inadequate hazard analysis leading to underestimated SIL requirements
- Treating SIL certification as a documentation exercise rather than a design discipline
- Ignoring common cause failures (CCF) in redundant architectures
- Insufficient independence between safety function and protection layers
    `,
  },
];

export function getArticlesByCategory(category: Category): Article[] {
  return articles.filter((a) => a.category === category);
}

export function getFeaturedArticle(): Article | undefined {
  return articles.find((a) => a.featured);
}

export function getRecentArticles(count = 3): Article[] {
  return [...articles]
    .sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime())
    .slice(0, count);
}

export function getArticleBySlug(slug: string): Article | undefined {
  return articles.find((a) => a.slug === slug);
}

export function formatDate(dateStr: string, locale: "en" | "he" = "en"): string {
  const date = new Date(dateStr);
  return date.toLocaleDateString(locale === "he" ? "he-IL" : "en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });
}
